FEDERATION_SERVER="https://api.stellar.org/federation/" 

[[CURRENCIES]] 
name="Rupiah Token" 
code="RUPIAH" 
desc="Rupiah Token (Asset Code : RUPIAH) is tokenized currency for Indonesian Rupiah's Standardization (globally known as IDR or Rupiah) within blockchain." 
conditions="Buy RUPIAH to enter spesific market that secured by Rupiah Token." 
issuer="GARUDAPB2D3ARKILZNQ5UIP766PSXHZAPBJO4ZIZNBLAXBTVYADRP4RU" 
display_decimals=5 
image="https://rupiahtoken.top/logo.png"
